### ISSUE TITLE
 missing '}' when build

### ISSUE THREAD

**Issue by lyquocnam** [thereactivestack/meteor-webpack#141] opened 2016-04-02 03:11 UTC
when i build:
` meteor build ../.bin`
error:

```
Errors prevented bundling:
While minifying app stylesheet:
assets/style.css:11:3645: missing '}'

While processing files with webpack:webpack (for target os.windows.x86_32):
fs.js:666:18: ENOENT, no such file or directory 'D:\DEV\Meteor\WEBPACK\linhchi-1.3\node_modules\core-js'
at Object.fs.readdirSync (fs.js:666:18)
at addNpmPackage (packages/webpack:webpack/plugin/WebpackCompiler.js:655:21)
at readPackageJson (packages/webpack:webpack/plugin/WebpackCompiler.js:647:9)
at addNpmPackage (packages/webpack:webpack/plugin/WebpackCompiler.js:653:83)
at packages/webpack:webpack/plugin/WebpackCompiler.js:659:7
at Array.forEach (native)
at addNpmPackage (packages/webpack:webpack/plugin/WebpackCompiler.js:657:9)
at packages/webpack:webpack/plugin/WebpackCompiler.js:659:7
at Array.forEach (native)
at addNpmPackage (packages/webpack:webpack/plugin/WebpackCompiler.js:657:9)
at readPackageJson (packages/webpack:webpack/plugin/WebpackCompiler.js:647:9)
at compile (packages/webpack:webpack/plugin/WebpackCompiler.js:589:9)
at runWebpack (packages/webpack:webpack/plugin/WebpackCompiler.js:265:5)
at WebpackCompiler.processFilesForTarget (packages/webpack:webpack/plugin/WebpackCompiler.js:112:5)
```

if run meteor normally, nothing wrong...
this may a bug, i tried find error css code wrong, but not found !

**Comment by lyquocnam** [comment] 2016-04-02 03:56
all less and css files no error, i use css linter checked, all fined

**Comment by tokn136** [comment] 2016-04-02 10:24
This is a duplicate of #133.

**Comment by eXon** [comment] 2016-05-01 04:04
Closing this because it is a duplicate

**Closed by eXon** 2016-05-01 04:04 UTC
