### ISSUE TITLE
CPU performance

### ISSUE THREAD

**Issue by tomitrescak** [thereactivestack/meteor-webpack#70] opened 2016-03-03 05:16 UTC
Hi. I have noticed that my computer runs quite hot while executing the new meteor-webpack. While the 0.x version kept it at around 30%, the 1.0 is running node process at 90-100%.

I tried to find out what the problem is and it looks like it is the amount of files it is watching?
I tried it with a mantra application and found out that only adding following line `import {createApp} from "mantra-core";` to client/index.js raises processor from 16 to 50%. Adding line `import initContext from "./configs/context";` brought the processor to 95% and stayed there.

If you want I can give you repo for this.

**Comment by tomitrescak** [comment] 2016-03-03 05:39
Yup, all is good at 15-16% until I add this line:

`import { useDeps, composeWithTracker, compose, composeAll } from "mantra-core";`

After I add that line, I'm at 90-100%.

**Comment by tomitrescak** [comment] 2016-03-03 08:36
@exon I now understand the reason, I just don't know how to solve it.

1. The CPU load jumps a lot, when I reference an NPM package from my app
2. The CPU load is increasing steadily with every new NPM package I am adding.

As a result, it looks like webpack starts to watch for change in the node_modules directory after the first refrence from the user code.

Is it possible not to watch for changes inside node_modules, only watch for changes on package.json ?

**Comment by FGM** [comment] 2016-03-03 09:29
Are you on MacOS X too ? The problem I have on #67 does not occur with the same app on Linux. Notice I have this problem with meteor-webpack 0.4.4 anyway, hence before 1.0

**Comment by tomitrescak** [comment] 2016-03-03 10:14
Yes, I'm on Mac. Hmmm, this means ... Dear Docker ... Here we go;) well at least until this problem will be solved on Mac;)

**Comment by eXon** [comment] 2016-03-03 22:04
This is a duplicate of #67 so I'm closing this. I'll try different settings with my Mac to see how we can poll differently.

**Closed by eXon** 2016-03-03 22:04 UTC
