### ISSUE TITLE
Failed to parse SourceMap

### ISSUE THREAD

**Issue by sammkj** [thereactivestack/meteor-webpack#123] opened 2016-03-25 01:36 UTC
I'm having this issue whenever I use Chrome Dev Tools inspect.

**Comment by jbbr** [comment] 2016-03-28 11:15
This is due to the bug https://github.com/webpack/webpack/issues/91 - Unfortunately it's not fixed yet in the latest webpack release for all webpack source-map options/devtools, e.g. https://github.com/webpack/webpack/blob/3ed27836b488401a7e9be2de1491a868a8b6f123/lib/EvalSourceMapDevToolModuleTemplatePlugin.js#L10

A workaround would be to change the webpack devtool to something else. e.g "source-map". As this is not currently possible in `webpack.json` (see #127) you could add a file `webpack.conf.js` to your project with the following content:

```
module.exports = {
  devtool: 'source-map'
}
```

I haven't tested this. It should work, but source-map generation will be a lot slower.

**Comment by eXon** [comment] 2016-03-29 11:46
I'm not sure of the problem but let me know if with 1.0.12 you're having the same problem

**Comment by jbbr** [comment] 2016-03-29 13:39
I still have this issue in 1.0.12. I'm on Chrome dev 50.0.
Probably this is not yet in Chrome stable channel.

**Comment by sammkj** [comment] 2016-03-29 16:51
This is fixed in 1.0.12. I'm on Chrome v49.0.2623.108.

**Comment by jbbr** [comment] 2016-03-31 21:12
Unfortunately it's not yet fixed in Chrome 50+. I can confirm that it's working in Chrome stable 49 but in Chrome beta 50 I get

> "//@ sourceURL=" source URL declaration is deprecated, "//# sourceURL=" declaration should be used instead.

These messages are flooding the dev console, it's almost impossible to follow the real log.

**Comment by normancarcamo** [comment] 2016-05-02 16:07
Hi everyone I was having the same problem and I just make a new file with the same name of the error, in my case was:

Failed to parse SourceMap: http://0.0.0.0:4000/app/wrapStatelessFunction.js.map 

I never before had to use it. After the file is created I had to make a new search on google and I realize that I am using react-css-modules so I found the file on github: https://github.com/inxilpro/react-bem-decorator/blob/master/dist/wrapStatelessFunction.js.map

**Closed** 2016-05-07 15:17 UTC

**Comment by Relic180** [comment] 2016-09-27 04:27
I was seeing the error on Chrome 53, webpack 1.13.2, but it appeared to be 1 specific map file that could not be parsed (there were 2 other bundles loaded on the page which also had maps, but threw no parsing errors).

While trying out several fairly random things, I eventually tried added several additional bundles to the page I was testing on, which threw several expected JS errors but I didn't see the "unable to parse" error anymore.

Upon removing the excess bundles, the page loads find now and appears to have no problem with any of the maps.

No clue why.
