### ISSUE TITLE
Meteor 1.3 + Webpack + testing

### ISSUE THREAD

**Issue by qimingfang** [thereactivestack/meteor-webpack#79] opened 2016-03-05 04:45 UTC
I've been following along the testing patterns in Meteor 1.3 beta (https://forums.meteor.com/t/a-first-implementation-of-meteor-app-testing-for-1-3/17097/41), but found that when I run the testing server alongside meteor-webpack, I continue to get an `Error: listen EADDRINUSE` error even when I run the tests with `--port 3100.`

The error happens in [WebpackCompiler](https://github.com/thereactivestack/meteor-webpack/blob/master/packages/webpack/plugin/WebpackCompiler.js#L621) I think. Are there any guidelines for Meteor 1.3 testing patterns with meteor-webpack?

**Comment by eXon** [comment] 2016-03-05 13:19
I will take a look at this. Testing is for sure very important to this project and I want to make sure it is working the same way than with regular Meteor 1.3.

**Comment by tonyxiao** [comment] 2016-03-05 23:54
@tomitrescak In your typescript + meteor + mantra + webpack example did you manage to get testing working?

**Comment by tomitrescak** [comment] 2016-03-07 08:03
@tonyxiao try this repo https://github.com/mantrajs/kickstart-mantrajs-webpack-typescript it has everything working

**Comment by tonyxiao** [comment] 2016-03-07 17:13
@tomitrescak do you have an example with meteor 1.3?

**Comment by tomitrescak** [comment] 2016-03-07 20:26
No, I don't. Why do you need 1.3?

**Comment by tonyxiao** [comment] 2016-03-07 20:53
Hmm good point I'm not sure. Is it suppose to have better performance or other enhancements in addition to better NPM integration?

**Comment by tomitrescak** [comment] 2016-03-08 00:24
Well, exon claims that it is fully compatible with 1.3. I've seen someone posting some issues and haven't tested myself, but in theory you should be able just to replace 1.2 with 1.3 and life shall be peachy.

**Comment by genyded** [comment] 2016-04-12 15:56
There are major deltas between 1.2 and 1.3. Root folders (e.g. imports in 1.3 which has no meaning in 1.2), How data is pulled (getMeteorData vs createContainer), the packaging system and being able to use NPM for React and other stuff, and so on. So it's probably safer to say it's compatible with 1.3 in 1.2 mode or something along those lines.

Most people who are going to use 1.3 are probably doing that to use it's features (and probably with the latest React via NPM is they are using React for the view layer). So while The Reactive Stack has been a great stepping stone for pre 1.3 webpack integration, it does not seem like it's currently up to par with a true 1.3 based Meteor app.

I've been using both for over a year and they seem to be moving in different directions... Meteor towards externalizing a lot and reactive stack towards integrating more into Meteor proper. As much as I love the Reactive Stack, I too am now pursuing other options more in line with where things seem to be shifting in general.

**Comment by laurentpayot** [comment] 2016-04-22 20:49
@eXon is there a way to run unit tests with meteor-webpack ? The official `meteor test` command does not detect test files...

**Comment by laurentpayot** [comment] 2016-05-04 21:00
For those interested I ended up using Chimp for my "full app tests" thanks to their `server.execute()` function. Just load your assertion library on the server before. `executeAsync()` also works for client-side tests.

**Comment by laurentpayot** [comment] 2016-05-13 09:51
meteor-webpack 1.3.0 has just been released with `meteor test` support! Thank you @eXon , I'm going to "test" that :smiley:

**Comment by eXon** [comment] 2016-05-13 12:09
@laurentpayot Let me know if it works great. Everything seems OK with the unit tests but I'm not sure it's working with the full app tests.

**Comment by laurentpayot** [comment] 2016-05-13 12:12
@eXon  Well I just opened #162

**Comment by laurentpayot** [comment] 2016-05-17 16:47
@eXon now that #162 is closed (`vue-meteor` issue) when running tests with `meteor test --driver-package practicalmeteor:mocha` I can see that mocha web reporter is not working, is that normal?

**Comment by eXon** [comment] 2016-05-18 01:16
@laurentpayot No. What's going on? I need more than just not working.

**Comment by laurentpayot** [comment] 2016-05-19 21:39
In my [repo](https://github.com/laurentpayot/meteor-webpack-vue-tests) I have [a file with a passing test and a failing test](https://github.com/laurentpayot/meteor-webpack-vue-tests/blob/master/meteor/src/app/collections/obvious.tests.coffee).

- When  the failing test is commented and the other test passes:
On my console I Have:
```
$ meteor test --driver-package practicalmeteor:mocha
[[[[[ Tests ]]]]]                             

=> Started proxy.                             
=> Started MongoDB.                           
=> Started your app.                          
                                              
=> App running at: http://localhost:3000/     
I20160519-23:22:40.833(2)? MochaRunner.runServerTests: Starting server side tests with run id csmhv6zSAt9cHhnqk
W20160519-23:22:40.910(2)? (STDERR) MochaRunner.runServerTests: failures: 0
```
On my browser (Chromium) I have:
```
Client tests
passes: 0failures: 0duration: 0s
 
Server tests
passes: 0failures: 0duration: 0s
```
- When the failing test is not commented:

On my console I have:
```
$ meteor test --driver-package practicalmeteor:mocha
[[[[[ Tests ]]]]]                             

=> Started proxy.                             
=> Started MongoDB.                           
W20160519-23:13:24.418(2)? (STDERR)           
W20160519-23:13:24.419(2)? (STDERR) /home/laurent/.meteor/packages/meteor-tool/.1.3.2_4.19r443t++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
W20160519-23:13:24.419(2)? (STDERR)             				throw(ex);
W20160519-23:13:24.419(2)? (STDERR)             				      ^
W20160519-23:13:24.658(2)? (STDERR) AssertionError: expected false to be true
W20160519-23:13:24.659(2)? (STDERR)     at Assertion.<anonymous> (packages/practicalmeteor_chai.js:1231:10)
W20160519-23:13:24.659(2)? (STDERR)     at Assertion.Object.defineProperty.get (packages/practicalmeteor_chai.js:4095:29)
W20160519-23:13:24.659(2)? (STDERR)     at Function.assert.isTrue (packages/practicalmeteor_chai.js:2793:31)
W20160519-23:13:24.659(2)? (STDERR)     at Suite.<anonymous> (webpack:///src/app/collections/obvious.tests.coffee:3:1)
W20160519-23:13:24.659(2)? (STDERR)     at context.describe.context.context (packages/practicalmeteor:mocha/lib/interfaces/bdd.js:47:10)
W20160519-23:13:24.659(2)? (STDERR)     at Suite.<anonymous> (webpack:///src/app/collections/obvious.tests.coffee:3:1)
W20160519-23:13:24.659(2)? (STDERR)     at context.describe.context.context (packages/practicalmeteor:mocha/lib/interfaces/bdd.js:47:10)
W20160519-23:13:24.659(2)? (STDERR)     at Object.module.exports (webpack:///src/app/collections/obvious.tests.coffee:5:1)
W20160519-23:13:24.659(2)? (STDERR)     at __webpack_require__ (webpack:/webpack/bootstrap 41be0342e805b0aeddd5:22:1)
W20160519-23:13:24.659(2)? (STDERR)     at webpackContext (webpack:/. ^\.\/.*$:29:1)
=> Exited with code: 8                        
W20160519-23:14:23.628(2)? (STDERR)           
W20160519-23:14:23.629(2)? (STDERR) /home/laurent/.meteor/packages/meteor-tool/.1.3.2_4.19r443t++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
W20160519-23:14:23.629(2)? (STDERR)             				throw(ex);
W20160519-23:14:23.630(2)? (STDERR)             				      ^
W20160519-23:14:23.922(2)? (STDERR) AssertionError: expected false to be true
W20160519-23:14:23.922(2)? (STDERR)     at Assertion.<anonymous> (packages/practicalmeteor_chai.js:1231:10)
W20160519-23:14:23.922(2)? (STDERR)     at Assertion.Object.defineProperty.get (packages/practicalmeteor_chai.js:4095:29)
W20160519-23:14:23.922(2)? (STDERR)     at Function.assert.isTrue (packages/practicalmeteor_chai.js:2793:31)
W20160519-23:14:23.922(2)? (STDERR)     at Suite.<anonymous> (webpack:///src/app/collections/obvious.tests.coffee:3:1)
W20160519-23:14:23.922(2)? (STDERR)     at context.describe.context.context (packages/practicalmeteor:mocha/lib/interfaces/bdd.js:47:10)
W20160519-23:14:23.922(2)? (STDERR)     at Suite.<anonymous> (webpack:///src/app/collections/obvious.tests.coffee:3:1)
W20160519-23:14:23.922(2)? (STDERR)     at context.describe.context.context (packages/practicalmeteor:mocha/lib/interfaces/bdd.js:47:10)
W20160519-23:14:23.922(2)? (STDERR)     at Object.module.exports (webpack:///src/app/collections/obvious.tests.coffee:5:1)
W20160519-23:14:23.922(2)? (STDERR)     at __webpack_require__ (webpack:/webpack/bootstrap 41be0342e805b0aeddd5:22:1)
W20160519-23:14:23.922(2)? (STDERR)     at webpackContext (webpack:/. ^\.\/.*$:29:1)
=> Exited with code: 8                        
W20160519-23:15:23.028(2)? (STDERR)           
W20160519-23:15:23.029(2)? (STDERR) /home/laurent/.meteor/packages/meteor-tool/.1.3.2_4.19r443t++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
W20160519-23:15:23.029(2)? (STDERR)             				throw(ex);
W20160519-23:15:23.029(2)? (STDERR)             				      ^
W20160519-23:15:23.330(2)? (STDERR) AssertionError: expected false to be true
W20160519-23:15:23.330(2)? (STDERR)     at Assertion.<anonymous> (packages/practicalmeteor_chai.js:1231:10)
W20160519-23:15:23.330(2)? (STDERR)     at Assertion.Object.defineProperty.get (packages/practicalmeteor_chai.js:4095:29)
W20160519-23:15:23.330(2)? (STDERR)     at Function.assert.isTrue (packages/practicalmeteor_chai.js:2793:31)
W20160519-23:15:23.330(2)? (STDERR)     at Suite.<anonymous> (webpack:///src/app/collections/obvious.tests.coffee:3:1)
W20160519-23:15:23.330(2)? (STDERR)     at context.describe.context.context (packages/practicalmeteor:mocha/lib/interfaces/bdd.js:47:10)
W20160519-23:15:23.330(2)? (STDERR)     at Suite.<anonymous> (webpack:///src/app/collections/obvious.tests.coffee:3:1)
W20160519-23:15:23.330(2)? (STDERR)     at context.describe.context.context (packages/practicalmeteor:mocha/lib/interfaces/bdd.js:47:10)
W20160519-23:15:23.331(2)? (STDERR)     at Object.module.exports (webpack:///src/app/collections/obvious.tests.coffee:5:1)
W20160519-23:15:23.331(2)? (STDERR)     at __webpack_require__ (webpack:/webpack/bootstrap 41be0342e805b0aeddd5:22:1)
W20160519-23:15:23.331(2)? (STDERR)     at webpackContext (webpack:/. ^\.\/.*$:29:1)
=> Exited with code: 8                        
=> Your application is crashing. Waiting for file change.
```
On my browser I have:
```
Your app is crashing. Here's the latest log:
/home/laurent/.meteor/packages/meteor-tool/.1.3.2_4.19r443t++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:267
						throw(ex);
						      ^
AssertionError: expected false to be true
    at Assertion.<anonymous> (packages/practicalmeteor_chai.js:1231:10)
    at Assertion.Object.defineProperty.get (packages/practicalmeteor_chai.js:4095:29)
    at Function.assert.isTrue (packages/practicalmeteor_chai.js:2793:31)
    at Suite.<anonymous> (webpack:///src/app/collections/obvious.tests.coffee:3:1)
    at context.describe.context.context (packages/practicalmeteor:mocha/lib/interfaces/bdd.js:47:10)
    at Suite.<anonymous> (webpack:///src/app/collections/obvious.tests.coffee:3:1)
    at context.describe.context.context (packages/practicalmeteor:mocha/lib/interfaces/bdd.js:47:10)
    at Object.module.exports (webpack:///src/app/collections/obvious.tests.coffee:5:1)
    at __webpack_require__ (webpack:/webpack/bootstrap 41be0342e805b0aeddd5:22:1)
    at webpackContext (webpack:/. ^\.\/.*$:29:1)
Exited with code: 8
Your application is crashing. Waiting for file change.
```

So it looks like on my machine (Ubuntu Desktop 16.04) the passing tests are not reported to the browser and as soon as a test fails the runner crashes.

**Comment by eXon** [comment] 2016-06-11 15:04
@laurentpayot Not sure this is relevant to this bug issue. Can you make another bug issue with clear steps to reproduce? I'll take a look.

**Closed by eXon** 2016-06-11 15:04 UTC

**Comment by laurentpayot** [comment] 2016-06-11 15:21
Well I'll wait for Meteor 1.4 release and I'll make a "copy and paste" CLI commands if the problem is still here…

**Comment by chmanie** [comment] 2016-08-05 11:40
Does anyone have a working example for Meteor 1.3 or 1.4? I don't know where to put my tests to be recognised correctly. Especially the client tests seem to be hard to integrate.

I have them in `client/imports`. When it runs the client tests the generated `testFiles` array generated by `WebpackTestRunner` is a mess (it just contains a weird mixture of all the directories I have plus the server files).

Sadly, that makes webpack unusable for me :(

Having said that, again, thank you so much for all the effort you put into this project so far. I really appreciate it. If I can get the `WebpackTestRunner` to recognise the correct files, I'll happily submit a PR.
