### ISSUE TITLE
meteor build issues

### ISSUE THREAD

**Issue by lucidprogrammer** [thereactivestack/meteor-webpack#140] opened 2016-04-01 15:29 UTC
What is the recommended approach for building when using meteor-webpack.
meteor build --directory ~/mydir
 (meteor --production works fine), but I do need to create a bundle.

meteor build --directory ~/mydir always fails. (missing core_js etc is looked in the project's node_module path. NODE_PATH which has these stuff from dev_bundle is not recognized.)

**Comment by lucidprogrammer** [comment] 2016-04-01 17:02
anyway the created build works. But meteor-webpack does not realise its is production
I see the following, where to give this to avoid getting these errors.
if (options) {
      IS_DEBUG = options.buildMode !== 'production';
    }

**Comment by lucidprogrammer** [comment] 2016-04-02 05:56
Was investigating this issue further. This error is coming from iles = _fs.readdirSync(folder);

Adding a try/catch around it solves the issue. I am not sure of the implication of this as I don't know the internals of webpack @eXon 

Mostly it looks for node_modules already in dev_bundle/lib/node_modules (of the meteor installation) For example (
`{ [Error: ENOENT, no such file or directory '/root/myttnc/src/webapp/node_modul$  errno: 34,
  code: 'ENOENT',
  path: '/root/myttnc/src/webapp/node_modules/core-js/',
  syscall: 'readdir' }`

But it does look for items not inside dev_bundle/lib/node_modules too. 

`function addNpmPackage(configFile, packageName, currentPath = '/', addedPackages) {
  const folder = CWD + '/node_modules/' + packageName + currentPath;
  let files = [];
  try{
    files = _fs.readdirSync(folder);
  }catch(e){console.log(e);}`

Let me know if running by a try/catch where those are not added can cause an issue which I don't immediately see. (the built bundle works without any conspicuous problems.

**Comment by menelike** [comment] 2016-04-02 08:16
This is a duplicate of https://github.com/thereactivestack/meteor-webpack/issues/133

**Comment by lucidprogrammer** [comment] 2016-04-26 15:03
As of now with METEOR@1.3.2.4, this package cannot build.
comment out the following and the above mentioned try catch is needed for the build to succeed.
// webpackConfig.plugins.push(new webpack.optimize.UglifyJsPlugin());

**Comment by menelike** [comment] 2016-04-26 15:09
@lucidprogrammer confirmed, exactly my solution. I added standard-minifier-js instead, this seems to work for production. (tested against 'webpack': '1.13.0')

**Comment by eXon** [comment] 2016-05-01 04:03
Closing this since it is a duplicate

**Closed by eXon** 2016-05-01 04:03 UTC
